fix: initalize routes of list pages
verless/verless pull request #188
Opened 2020-10-02 13:16 UTC by hmble

Fix for issue #181 

I don't know how to test is this right or not. 
I will update this PR if any changes are needed.

2020-10-02 13:30 UTC, dominikbraun commented
Sorry, I managed to write `Route: ...` in my example. My bad.

`Route` already is included inside `Page`, so the syntax is:

```go
&model.ListPage{
	Page: model.Page{
		Route: tagsDir + "/" + key,
	},
	Pages: make([]*model.Page, 0),
}
```

2020-10-02 20:06 UTC, dominikbraun requested changes
As I mentioned, I made a mistake when describing the solution in #180. 😅

2020-10-02 20:06 UTC, dominikbraun commented on model/page.go
> +	Route string
`Route` can be removed since it already exists in `Page`.

2020-10-02 20:06 UTC, dominikbraun commented on plugin/tags/tags.go
> +		Route: tagsDir + "/" + key,
Therefore, this becomes

```
Page: model.Page{
	Route: tagsDir + "/" + key,
},
```

2020-10-03 07:27 UTC, dominikbraun approved these changes
LGTM 👍

2020-10-03 07:29 UTC, merged

2020-10-03 08:22 UTC, hmble commented
Hey @dominikbraun I have a request which I sent you on your mail at ( mail at dominikibraun.io ) 
Can you please check that for me ? It will help me a lot.