add 3rd-Party installation method
verless/verless pull request #229
Opened 2020-10-21 20:27 UTC by codenoid

add 3rd-Party installation method via gobinaries.com

2020-10-21 20:47 UTC, aligator commented
Thanks, didn't know that service, yet :-)

But I have some things to discuss:
1. Is this really needed as we provide releases with built binaries (for the most important architectures and systems) very regularly? (If any specific architecture+os combination is needed, just create a issue.)
2. One problem with this could be that this service does not inject the version, which is a problem if someone creates a issue and tries to use `verless -v`

To solve 2. we could just add a info that these builds are not supported and issues should be always tested using official releases.

2020-10-21 20:56 UTC, aligator requested changes
To be discussed

2020-10-24 20:19 UTC, dominikbraun requested changes
> To solve 2. we could just add a info that these builds are not supported and issues should be always tested using the latest official release.

Let's do that and we're good to go.

2020-11-08 17:39 UTC, aligator commented on README.md
> +
```suggestion

__Unsupported, use the official builds when reporting issues!__
```

2024-01-23 21:43 UTC, closed without merging