Change css directory to assets directory in example, closes #246
verless/verless pull request #250
Opened 2020-12-05 08:02 UTC by FelixMohr

closes #246

2020-12-06 13:20 UTC, aligator requested changes
Thanks for the PR.
Could you please adapt all places like I told in the comment?
After that it should be ok :-)

2020-12-06 13:20 UTC, aligator commented on example/themes/default/templates/list-page.html
> +        <link rel="stylesheet" type="text/css" href="/assets/style.css" />
I think it would be better to still use a subfolder `assets/css`.
So here it would be `/assets/css/style.css`.

2020-12-06 18:45 UTC, dominikbraun approved these changes
LGTM 👍

2020-12-06 21:00 UTC, aligator requested changes
Nice, thank you!

2020-12-06 21:00 UTC, aligator approved these changes

2021-02-28 10:07 UTC, dominikbraun commented
As a part of verless v0.6.0, I'm going to merge this :-)

2021-02-28 10:07 UTC, merged